# This is a basic workflow to help you get started with Actions
name: CICD for Development
 
# Controls when the action will run. 
on:
  # mainブランチにpush,margeされたタイミングで発火する
  push:
    branches: [ main ]
 
  # 手動で実行する
  workflow_dispatch:
 
jobs:
 
  build:
    name: Build And Upload to Devlopment S3 
    runs-on: ubuntu-latest
 
    steps:
 
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: npm install
       
      # ビルド
      - name: Build
        run: npm run build
       
      # S3へのデプロイ準備
      - name: Configure AWS credentials from account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # Secretsで登録したキーを設定
          aws-access-key-id: ${{ secrets.CICD_DEVELOP_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_DEVELOP_AWS_SECRET_ACCESS_KEY }}
          # S3のリージョン
          aws-region: ap-northeast-1
 
      # デプロイ（ファイルをアップロード）
      - name: Copy Files to s3
        run: |
          aws s3 sync ./build s3://docusaurus-template-xmkyt
